package com.ryougichan.payment.service.impl;

import com.alipay.api.AlipayApiException;
import com.alipay.api.AlipayClient;
import com.alipay.api.DefaultAlipayClient;
import com.alipay.api.domain.AlipayTradePagePayModel;
import com.alipay.api.domain.AlipayTradeWapPayModel;
import com.alipay.api.request.AlipayTradePagePayRequest;
import com.alipay.api.request.AlipayTradeWapPayRequest;
import com.alipay.api.response.AlipayTradePagePayResponse;
import com.ryougichan.payment.entity.AlipayConfig;
import com.ryougichan.payment.service.IOnlinePay;

import javax.servlet.http.HttpServletRequest;
import java.util.Date;

public class Alipay implements IOnlinePay {

    /**
     * Alipay Configuration
     */
    AlipayConfig alipayConfig;

    /**
     * Dispatch payment request to Alipay sever
     *
     * @param payWay    Way of payment, including `QR Code Payment`, `APP Payment`, `In-App Web-based Payment(H5 Payment)` and etc.
     * @param orderId   Order number generated by sever
     * @param payAmount Amount Paid
     * @return Return whatever the Alipay sever return(A HTML <form>)
     */
    @Override
    public String pay(String payWay, String orderId, Double payAmount) {
        // Init Alipay configuration
        this.initAlipayConfig();
        //******************************** Parameters Setting Start *********************************
        // Payment amount
        String total_amount = payAmount.toString();
        // Payment order name, required
        String subject = "Product Name";
        // Description of product, optional
        String body = "";
        // Expire time
        String timeout_express = "2h";
        // Product code, an Alipay identification code, default: `FAST_INSTANT_TRADE_PAY`, means QR Code Payment
        String product_code = payWay == null || payWay.trim().equals("")? AlipayConfig.PRODUCT_CODE_PAGE : payWay;
        //******************************** Parameters Setting End *********************************

        AlipayClient client = new DefaultAlipayClient(alipayConfig.getURL(), alipayConfig.getAppID(), alipayConfig.getPrivateKey(), alipayConfig.getFormat(), alipayConfig.getCharset(), alipayConfig.getAlipayPublicKey(),alipayConfig.getSignType());

        String form = null;

        if(product_code.equals("QUICK_WAP_WAY")) {
            /////////// In-App Web-based Payment(H5 Payment) ///////////
            AlipayTradeWapPayRequest alipayRequest = new AlipayTradeWapPayRequest();
            //******************************** Pay request parameter setting start *********************************
            AlipayTradeWapPayModel model = new AlipayTradeWapPayModel();
            model.setOutTradeNo(orderId);
            model.setSubject(subject);
            model.setTotalAmount(total_amount);
            model.setBody(body);
            model.setTimeoutExpress(timeout_express);
            model.setProductCode(product_code);
            alipayRequest.setBizModel(model);
            alipayRequest.setNotifyUrl(alipayConfig.getNotifyUrl());
            alipayRequest.setReturnUrl(alipayConfig.getReturnUrl());
            //******************************** Pay request parameter setting end *********************************

            try {
                form = client.pageExecute(alipayRequest).getBody();
                return form;
            } catch (AlipayApiException e) {
                // TODO: Logging
                return null;
            }
        } else {
            /////////// Default: QR Code Payment ///////////
            AlipayTradePagePayRequest alipayRequest = new AlipayTradePagePayRequest();
            //******************************** Pay request parameter setting start *********************************
            AlipayTradePagePayModel model = new AlipayTradePagePayModel();
            model.setOutTradeNo(orderId);
            model.setSubject(subject);
            model.setTotalAmount(total_amount);
            model.setBody(body);
            model.setTimeoutExpress(timeout_express);
            model.setProductCode(product_code);
            alipayRequest.setBizModel(model);
            alipayRequest.setReturnUrl(alipayConfig.getReturnUrl());
            alipayRequest.setNotifyUrl(alipayConfig.getNotifyUrl());
            //******************************** Pay request parameter setting end *********************************

            AlipayTradePagePayResponse response;
            try {
                response = client.pageExecute(alipayRequest);
                if(response.isSuccess()) {
                    form = response.getBody();
                } else {
                    // TODO: Logging
                }
                return form;
            } catch (AlipayApiException e) {
                // TODO: Logging
                return null;
            }
        }
    }

    /**
     * Receive payment callback from Alipay sever if supported
     *
     * @param request The javax.servlet.http.HttpServletRequest object itself
     * @return A notify message to tell Alipay sever that we have received this notify callback
     * @deprecated The method defined here is for example only because there are specific business logic included in usual
     */
    @Override
    public String receivePaymentNotify(HttpServletRequest request) {
        return null;
    }

    /**
     * Dispatch refund request to Alipay sever
     *
     * @param orderId      Order number generated by sever
     * @param tradeId      The trade number generated by Alipay sever
     * @param totalAmount  The total trade amount of the order to refund
     * @param refundAmount The amount of the refund(Partial refund supported if possible)
     * @return Return whatever the Alipay sever return
     */
    @Override
    public String refund(String orderId, String tradeId, Double totalAmount, Double refundAmount) {
        return null;
    }

    /**
     * Receive refund callback from Alipay sever if supported
     *
     * @param request The javax.servlet.http.HttpServletRequest object itself
     * @return A notify message to tell Alipay sever that we have received this notify callback
     * @deprecated The method defined here is for example only because there are specific business logic included in usual
     */
    @Override
    public String receiveRefundNotify(HttpServletRequest request) {
        return null;
    }

    /**
     * Dispatch transactions inquiry request to Alipay sever
     *
     * @param orderId Order number generated by sever
     * @param tradeId The trade number generated by Alipay sever
     * @return Return whatever the Alipay sever return
     */
    @Override
    public String query(String orderId, String tradeId) {
        return null;
    }

    /**
     * Dispatch transactions close request to Alipay sever
     *
     * @param orderId Order number generated by sever
     * @param tradeId The trade number generated by Alipay sever
     * @return Return whatever the Alipay sever return
     */
    @Override
    public String close(String orderId, String tradeId) {
        return null;
    }

    /**
     * Dispatch refund inquiry request to Alipay sever
     *
     * @param orderId  Order number generated by sever
     * @param tradeId  The trade number generated by Alipay sever
     * @param refundId Order refund number generated by sever when refund request dispatched
     * @return Return whatever the Alipay sever return
     */
    @Override
    public String refundQuery(String orderId, String tradeId, String refundId) {
        return null;
    }

    /**
     * Dispatch download bill request to access historical transaction list from Alipay sever
     *
     * @param billDate Bill time
     * @param billType Bill type
     * @return Return merchant offline bill download address
     */
    @Override
    public String downloadBill(Date billDate, String billType) {
        return null;
    }

    private void initAlipayConfig()
    {
        if(null == this.alipayConfig) {
            alipayConfig = new AlipayConfig();
        }
    }
}
