package com.ryougichan.payment.service.impl;

import com.ryougichan.payment.service.IOnlinePay;

import javax.servlet.http.HttpServletRequest;
import java.util.Date;

public class WeChatPay implements IOnlinePay {

    /**
     * Dispatch payment request to WeChat Pay sever
     *
     * @param payWay    Way of payment, including `QR Code Payment`, `APP Payment`, `In-App Web-based Payment(H5 Payment)` and etc.
     * @param orderId   Order number generated by sever
     * @param payAmount Amount Paid
     * @return Return whatever the WeChat Pay sever return
     */
    @Override
    public String pay(String payWay, String orderId, Double payAmount) {
        return null;
    }

    /**
     * Receive payment callback from WeChat Pay sever if supported
     *
     * @param request The javax.servlet.http.HttpServletRequest object itself
     * @return A notify message to tell WeChat Pay sever that we have received this notify callback
     * @deprecated The method defined here is for example only because there are specific business logic included in usual
     */
    @Override
    public String receivePaymentNotify(HttpServletRequest request) {
        return null;
    }

    /**
     * Dispatch refund request to WeChat Pay sever
     *
     * @param orderId      Order number generated by sever
     * @param tradeId      The trade number generated by WeChat Pay sever
     * @param totalAmount  The total trade amount of the order to refund
     * @param refundAmount The amount of the refund(Partial refund supported if possible)
     * @return Return whatever the WeChat Pay sever return
     */
    @Override
    public String refund(String orderId, String tradeId, Double totalAmount, Double refundAmount) {
        return null;
    }

    /**
     * Receive refund callback from WeChat Pay sever if supported
     *
     * @param request The javax.servlet.http.HttpServletRequest object itself
     * @return A notify message to tell WeChat Pay sever that we have received this notify callback
     * @deprecated The method defined here is for example only because there are specific business logic included in usual
     */
    @Override
    public String receiveRefundNotify(HttpServletRequest request) {
        return null;
    }

    /**
     * Dispatch transactions inquiry request to WeChat Pay sever
     *
     * @param orderId Order number generated by sever
     * @param tradeId The trade number generated by WeChat Pay sever
     * @return Return whatever the WeChat Pay sever return
     */
    @Override
    public String query(String orderId, String tradeId) {
        return null;
    }

    /**
     * Dispatch transactions close request to WeChat Pay sever
     *
     * @param orderId Order number generated by sever
     * @param tradeId The trade number generated by WeChat Pay sever
     * @return Return whatever the WeChat Pay sever return
     */
    @Override
    public String close(String orderId, String tradeId) {
        return null;
    }

    /**
     * Dispatch refund inquiry request to WeChat Pay sever
     *
     * @param orderId  Order number generated by sever
     * @param tradeId  The trade number generated by WeChat Pay sever
     * @param refundId Order refund number generated by sever when refund request dispatched
     * @return Return whatever the WeChat Pay sever return
     */
    @Override
    public String refundQuery(String orderId, String tradeId, String refundId) {
        return null;
    }

    /**
     * Dispatch download bill request to access historical transaction list from WeChat Pay sever
     *
     * @param billDate Bill time
     * @param billType Bill type
     * @return Return merchant bill data with text table format
     */
    @Override
    public String downloadBill(Date billDate, String billType) {
        return null;
    }
}
